<?xml version="1.0" encoding="utf-8"?><Database Name="Database1" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\Database1.mdf;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="Database1ConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.bju" Member="bju_items">
    <Type Name="bju_items">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NChar(20)" CanBeNull="true" />
      <Column Name="b" Type="System.Decimal" DbType="Decimal(18,1)" CanBeNull="true" />
      <Column Name="j" Type="System.Decimal" DbType="Decimal(18,1)" CanBeNull="true" />
      <Column Name="u" Type="System.Decimal" DbType="Decimal(18,1)" CanBeNull="true" />
      <Column Name="kal" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
</Database>